# Generated by Django 3.0.5 on 2020-07-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('ifsc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
    ]
